--1. SIMPLE CASE STATEMENT

--CASE SELECTOR
--WHEN SELECTOR_VALUE_1 THEN STATEMENT_1
--WHEN SELECTOR_VALUE_2 THEN STATEMENT_2
--.
--.
--WHEN SELECTOR_VALUE_N THEN STATEMENT_N
--ELSE ELSE_STATEMENT
---END CASE;


DECLARE
V_GRADE CHAR(1);
BEGIN
V_GRADE := :GRADE;

CASE V_GRADE
WHEN 'A' THEN DBMS_OUTPUT.PUT_LINE('EXCELLENT');
WHEN 'B' THEN DBMS_OUTPUT.PUT_LINE('VERY GOOD');
WHEN 'C' THEN DBMS_OUTPUT.PUT_LINE('GOOD');
WHEN 'D' THEN DBMS_OUTPUT.PUT_LINE('FAIR');
WHEN 'F' THEN DBMS_OUTPUT.PUT_LINE('POOR');
ELSE DBMS_OUTPUT.PUT_LINE('NO SUCH GRADE');
END CASE;
END;


--2. SEARCHED CASE STATEMENT

--CASE
--WHEN CONDITION_1 THEN STATEMENT_1
--WHEN CONDITION_2 THEN STATEMENT_2
--.
--.
--WHEN CONDITION_N THEN STATEMENT_N
--ELSE ELSE_STATEMENT
---END CASE;

DECLARE
V_GRADE CHAR(1);
BEGIN
V_GRADE := :GRADE;

CASE
WHEN V_GRADE = 'A' THEN DBMS_OUTPUT.PUT_LINE('EXCELLENT');
WHEN V_GRADE = 'B' THEN DBMS_OUTPUT.PUT_LINE('VERY GOOD');
WHEN V_GRADE = 'C' THEN DBMS_OUTPUT.PUT_LINE('GOOD');
WHEN V_GRADE = 'D' THEN DBMS_OUTPUT.PUT_LINE('FAIR');
WHEN V_GRADE = 'F' THEN DBMS_OUTPUT.PUT_LINE('POOR');
ELSE DBMS_OUTPUT.PUT_LINE('NO SUCH GRADE');
END CASE;
END;