--check whether a given character is letter or digit

SET SERVEROUTPUT ON;

DECLARE
V_CHAR CHAR(1) := '.';

BEGIN

IF (V_CHAR >= 'A' AND V_CHAR <= 'Z') OR (V_CHAR >= 'a' AND V_CHAR <= 'z')  THEN
DBMS_OUTPUT.PUT_LINE ('THE CHARACTER IS A LETTER');
ELSIF (V_CHAR >= '0' AND V_CHAR <= '9') THEN
DBMS_OUTPUT.PUT_LINE ('THE CHARACTER IS A NUMBER');
ELSE
DBMS_OUTPUT.PUT_LINE ('THE CHARACTER IS NOT A NUMBER AND LETTER');
END IF;

END;