SET SERVEROUTPUT ON;

--1. STATIC FUNCTION
CREATE OR REPLACE FUNCTION XX_SUM_FUNC
RETURN NUMBER
AS

V_1 NUMBER := 20;
V_2 NUMBER := 50;
V_TOTAL NUMBER;

BEGIN

SELECT V_1 + V_2 INTO V_TOTAL FROM DUAL;
DBMS_OUTPUT.PUT_LINE('SUM OF TWO NUMBERS : '||V_TOTAL);
RETURN V_TOTAL;

END;

SELECT XX_SUM_FUNC FROM DUAL;


--2.DYNAMIC FUNCTION
CREATE OR REPLACE FUNCTION XX_SUM_FUNC2 (V_1 NUMBER, V_2 NUMBER)
RETURN NUMBER
AS

V_TOTAL NUMBER;

BEGIN

SELECT V_1 + V_2 INTO V_TOTAL FROM DUAL;
DBMS_OUTPUT.PUT_LINE('SUM OF TWO NUMBERS : '||V_TOTAL);
RETURN V_TOTAL;

END;

SELECT XX_SUM_FUNC2 (30, 90) FROM DUAL;