--1. if then statement

DECLARE 
V_HINDI NUMBER;
V_ENGLISH NUMBER;
V_MATHS NUMBER;

BEGIN
V_HINDI := :HINDI;
V_ENGLISH := :ENGLISH;
V_MATHS := :MATHS;

IF V_HINDI > 33 THEN
DBMS_OUTPUT.PUT_LINE('PASS IN HINDI SUBJECT');
END IF;

IF V_ENGLISH > 33 THEN
DBMS_OUTPUT.PUT_LINE('PASS IN ENGLISH SUBJECT');
END IF;

IF V_MATHS > 33 THEN
DBMS_OUTPUT.PUT_LINE('PASS IN MATHS SUBJECT');
END IF;

END;


--2. IF THEN ELSE STATEMENT

DECLARE 
V_HINDI NUMBER;
V_ENGLISH NUMBER;
V_MATHS NUMBER;

BEGIN
V_HINDI := :HINDI;
V_ENGLISH := :ENGLISH;
V_MATHS := :MATHS;

IF V_HINDI > 33 THEN
DBMS_OUTPUT.PUT_LINE('PASS IN HINDI SUBJECT');
ELSE
DBMS_OUTPUT.PUT_LINE('FAIL IN HINDI SUBJECT');
END IF;

IF V_ENGLISH > 33 THEN
DBMS_OUTPUT.PUT_LINE('PASS IN ENGLISH SUBJECT');
ELSE
DBMS_OUTPUT.PUT_LINE('FAIL IN ENGLISH SUBJECT');
END IF;

IF V_MATHS > 33 THEN
DBMS_OUTPUT.PUT_LINE('PASS IN MATHS SUBJECT');
ELSE
DBMS_OUTPUT.PUT_LINE('FAIL IN MATHS SUBJECT');
END IF;

END;


--2.1. NESTED IF THEN ELSE STATEMENT

DECLARE 
V_HINDI NUMBER;
V_ENGLISH NUMBER;
V_MATHS NUMBER;
V_TOTAL NUMBER;
V_PERCENT NUMBER;

BEGIN
V_HINDI := :HINDI;
V_ENGLISH := :ENGLISH;
V_MATHS := :MATHS;

IF V_HINDI IS NOT NULL THEN
    IF V_ENGLISH IS NOT NULL THEN
        IF V_MATHS IS NOT NULL THEN
            V_TOTAL := V_HINDI + V_ENGLISH + V_MATHS;
            V_PERCENT := V_TOTAL/3;
            DBMS_OUTPUT.PUT_LINE('TOTAL: '|| V_TOTAL || ', YOUR PERCENT: '|| V_PERCENT||'%');
        ELSE
        DBMS_OUTPUT.PUT_LINE('MATHS MARK IS BLANK');
        END IF;
    ELSE
    DBMS_OUTPUT.PUT_LINE('ENGLISH MARK IS BLANK');
    END IF;
ELSE
DBMS_OUTPUT.PUT_LINE('HINDI MARK IS BLANK');
END IF;

END;


--3. IF THEN ELSEIF STATEMENT

DECLARE 
V_HINDI NUMBER;
V_ENGLISH NUMBER;
V_MATHS NUMBER;
V_TOTAL NUMBER;
V_PERCENT NUMBER;

BEGIN
V_HINDI := :HINDI;
V_ENGLISH := :ENGLISH;
V_MATHS := :MATHS;

V_TOTAL := V_HINDI + V_ENGLISH + V_MATHS;
V_PERCENT := V_TOTAL/3;

IF V_PERCENT >= 90 THEN
DBMS_OUTPUT.PUT_LINE('EXCELLENT: '|| V_PERCENT||'%');

ELSIF V_PERCENT >= 70 AND V_PERCENT < 90 THEN
DBMS_OUTPUT.PUT_LINE('VERY GOOD: '|| V_PERCENT||'%');

ELSIF V_PERCENT >= 60 AND V_PERCENT < 70 THEN
DBMS_OUTPUT.PUT_LINE('GOOD: '|| V_PERCENT||'%');

ELSIF V_PERCENT >= 50 AND V_PERCENT < 60 THEN
DBMS_OUTPUT.PUT_LINE('FAIR: '|| V_PERCENT||'%');

ELSIF V_PERCENT >= 40 AND V_PERCENT < 50 THEN
DBMS_OUTPUT.PUT_LINE('POOR: '|| V_PERCENT||'%');

ELSE
DBMS_OUTPUT.PUT_LINE('FAIL: '|| V_PERCENT||'%');
END IF;

END;