--ADD EMPLOYEE
CREATE OR REPLACE PROCEDURE ADDEMPDETAILS 
(
    P_ID IN NUMBER,
    P_NAME IN VARCHAR2,
    P_EMAIL IN VARCHAR2,
    P_PHONENO IN NUMBER
)
IS
BEGIN
    INSERT INTO EMPLOYEETABLE (ID, NAME, EMAIL, PHONENO) VALUES (P_ID, P_NAME, P_EMAIL, P_PHONENO);
END;

EXECUTE ADDEMPDETAILS (3, 'PIYUSH NIMJE', 'PIYUSH.NIMJE@GMAIL.COM', 7894561231);

--SELECT * FROM EMPLOYEETABLE;

--UPDATEEMPLOYEE
CREATE OR REPLACE PROCEDURE UPDATEEMPDETAILS
(
    P_ID IN NUMBER,
    P_NAME IN VARCHAR2,
    P_EMAIL IN VARCHAR2,
    P_PHONENO IN NUMBER
)
IS
BEGIN
    UPDATE EMPLOYEETABLE SET  NAME = P_NAME, EMAIL = P_EMAIL, PHONENO = P_PHONENO WHERE ID = P_ID;
END;

EXECUTE UPDATEEMPDETAILS (3, 'PIYUSH NIMJE', 'piyush.n@gmail.com', 7894561231);

--DELETE EMPLOYEE
CREATE OR REPLACE PROCEDURE DELETEEMPDETAILS 
(
    P_ID IN NUMBER
)
IS
BEGIN
    DELETE FROM EMPLOYEETABLE WHERE ID = P_ID;
END;

EXECUTE DELETEEMPDETAILS (3);